version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      MYSQL_ROOT_PASSWORD: custom_root_password
      MYSQL_DATABASE: custom_database_name
      MYSQL_USER: custom_database_user
      MYSQL_PASSWORD: custom_database_password

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: custom_root_password
      MYSQL_DATABASE: custom_database_name
      MYSQL_USER: custom_database_user
      MYSQL_PASSWORD: custom_database_password
    ports:
      - "3306:3306"

