name: ci-test
run-name: ci-test
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose-file: "./compose.yml"
          test-container: "backend"
          test-command: "curl localhost:80"
    
      - uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose-file: "./compose.yml"
          test-container: "frontend"
          test-command: "curl localhost:3000"
