name: ci
run-name: "ci-$(date +'%Y-%m-%d')"
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: docker compose build 
      - name: run containers
        run: docker compose up -d
      - name: docker ps
        run: docker ps
      - name: test frontend
        run: sleep 10 && curl localhost:3000
      - run: sleep 3 && lsof -n -i -P | grep 3000
      - name: test backend
        run: sleep 200 && curl localhost:88
        
