name: ci
run-name: ci
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
      - run: docker compose build --no-cache
      - name: test backend
      - run: curl localhost:80
      - name: test frontend
      - run: curl localhost:3000
        
