name: self-hosted
run-name: sh
on:
  workflow_dispatch: 
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        name: add db vars
        env:
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        run: |
          rm -rf .env
          echo "MYSQL_DATABASE=$MYSQL_DATABASE" >> .env
          echo "MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD" >> .env
      - name: build
        run: sudo docker compose build 
      - name: run containers
        run:  sudo docker compose up -d
      - name: docker ps
        run: sudo docker ps
      - name: test frontend
        run: sleep 10 && curl localhost:3000
      - name: test backend
        run: sleep 5 && curl localhost:88
      - run: sudo docker compose down
      - shell: bash
        name: push images to jfrog
        env:
          DOCKER_USER: ${{ secrets.docker_USER }}
          DOCKER_TOKEN: ${{ secrets.docker_token }}
          VERSION: ${{github.run_number}}
        run: |
          echo $VERSION
          sudo docker login -u$DOCKER_USER -p$DOCKER_TOKEN tagal.jfrog.io
          sudo docker tag react-java0mysql-frontend tagal.jfrog.io/tagal/frontend:$VERSION
          sudo docker tag react-java0mysql-backend tagal.jfrog.io/tagal/backend:$VERSION
          sudo docker push tagal.jfrog.io/tagal/frontend:$VERSION
          sudo docker push tagal.jfrog.io/tagal/backend:$VERSION
          sudo docker tag mysql:8.0.27 tagal.jfrog.io/tagal/db:$VERSION
          sudo docker push tagal.jfrog.io/tagal/db:$VERSION
      - name: Trigger ArgoCD Sync
        run: |
          git clone git@github.com:tagaldev/eks-terraform.git
          pwd
          cd eks-terraform
          sed -i "s|image: tagal.jfrog.io/tagal/frontend:*.*|image: tagal.jfrog.io/tagal/frontend:${{github.run_number}}|g" manifest/app/frontend-deployment.yaml
          sed -i "s|image: tagal.jfrog.io/tagal/backend:*.*|image: tagal.jfrog.io/tagal/backend:${{github.run_number}}|g" manifest/app/backend-deployment.yaml
          sed -i "s|image: tagal.jfrog.io/tagal/db:*.*|image: tagal.jfrog.io/tagal/db:${{github.run_number}}|g" manifest/app/db-deployment.yaml
          git add .
          git commit -m "Trigger ArgoCD Sync"
          git push origin main
          
  notify:
    needs:
      - ci
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Send failure notification
        uses: cinotify/github-action@main
        with:
          to: ${{vars.EMAIL}}
          subject: Workflow failed
          body: The workflow failed, please check this on github actions
