name: self-hosted
run-name: sh
on:
  workflow_dispatch: 
  # push:
  # pull_request:
  #   branches:
  #     - main
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: sudo docker compose build 
      - name: run containers
        run:  sudo docker compose up -d
      - name: docker ps
        run: sudo docker ps
      - name: test frontend
        run: sleep 10 && curl localhost:3000
      - name: test backend
        run: sleep 5 && curl localhost:88
      - run: sudo docker compose down
      - shell: bash
        name: push images to jfrog
        env:
          JFROG_USER: ${{ secrets.JFROG_USER }}
          JFROG_TOKEN: ${{ secrets.JFROG_token }}
          VERSION: ${{github.run_number}}
        run: |
          echo $VERSION
          sudo docker image save react-java0mysql-frontend -o /tmp/react-java0mysql-frontend.tar
          sudo curl -u $JFROG_USER:$JFROG_TOKEN -X PUT "http://51.20.254.255:8082/artifactory/tagal/final-project/frontend/frontend.$VERSION.tar" -T /tmp/react-java0mysql-frontend.tar
          sudo docker image save react-java0mysql-backend -o /tmp/react-java0mysql-backend.tar
          sudo curl -u $JFROG_USER:$JFROG_TOKEN -X PUT "http://51.20.254.255:8082/artifactory/tagal/final-project/backend/backend.$VERSION.tar" -T /tmp/react-java0mysql-backend.tar
